package pqt.dss.accOpening.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 20 17:01:13 PKT 2016
// ---------------------------------------------------------------------
public interface AOAM extends ApplicationModule {
    void Apply();

    void DeleteCommit();

    void Rollback();

    void DssApprove();

    void callWorkflow(oracle.jbo.domain.Number p_document_id, String ApprovalType);

    String SearchAgent();

    void callAccOpenWorkflow(oracle.jbo.domain.Number p_document_id);
}

