package pqt.dss.accOpening.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 17 14:32:37 PKT 2016
// ---------------------------------------------------------------------
public interface DssAccountOpeningHeaderView extends ViewObject {
    void setNVC_WfDocumentId(oracle.jbo.domain.Number value);

    void accOpenSearchUser();
}

