package pqt.dss.accOpening.model.vo;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;

import pqt.dss.accOpening.model.vo.common.DssAccountOpeningHeaderView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 17 12:51:17 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssAccountOpeningHeaderViewImpl extends ViewObjectImpl implements DssAccountOpeningHeaderView {
    /**
     * This is the default constructor (do not remove).
     */
    public DssAccountOpeningHeaderViewImpl() {
    }

    /**
     * Returns the variable value for VC_Branch_Name.
     * @return variable value for VC_Branch_Name
     */
    public String getVC_Branch_Name() {
        return (String) ensureVariableManager().getVariableValue("VC_Branch_Name");
    }

    /**
     * Sets <code>value</code> for variable VC_Branch_Name.
     * @param value value to bind as VC_Branch_Name
     */
    public void setVC_Branch_Name(String value) {
        ensureVariableManager().setVariableValue("VC_Branch_Name", value);
    }

    /**
     * Returns the variable value for NVC_WfDocumentId.
     * @return variable value for NVC_WfDocumentId
     */
    public Number getNVC_WfDocumentId() {
        return (Number) ensureVariableManager().getVariableValue("NVC_WfDocumentId");
    }

    /**
     * Sets <code>value</code> for variable NVC_WfDocumentId.
     * @param value value to bind as NVC_WfDocumentId
     */
    public void setNVC_WfDocumentId(Number value) {
        ensureVariableManager().setVariableValue("NVC_WfDocumentId", value);
        this.exeViewCrieteria(value);
    }
    public void exeViewCrieteria(Number val) {
        ViewObject vo = this.getViewObject();
        ViewCriteria vc = this.getViewCriteria("NotificationViewCriteria");
        vo.applyViewCriteria(vc);
        vo.setNamedWhereClauseParam("NVC_WfDocumentId", val);
        vo.executeQuery();
    }

    /**
     * Returns the variable value for VC_Doc_No.
     * @return variable value for VC_Doc_No
     */
    public String getVC_Doc_No() {
        return (String) ensureVariableManager().getVariableValue("VC_Doc_No");
    }

    /**
     * Sets <code>value</code> for variable VC_Doc_No.
     * @param value value to bind as VC_Doc_No
     */
    public void setVC_Doc_No(String value) {
        ensureVariableManager().setVariableValue("VC_Doc_No", value);
    }

    public void accOpenSearchUser()
    {
              ViewCriteria vc = this.getViewCriteria("BranchViewCriteria");
              this.applyViewCriteria(vc);

              setWhereClause(null);
              FacesContext fctx = FacesContext.getCurrentInstance();
              ExternalContext ectx = fctx.getExternalContext();
              HttpSession userSession = (HttpSession) ectx.getSession(false);
              Object VUserID = userSession.getAttribute("pUserId") == null ? "268" : userSession.getAttribute("pUserId");
              setWhereClause("QRSLT.BRANCH_CODE_FK IN\n" + 
              "       (select A.BRANCH_CODE\n" + 
              "          from DSS_SM_USERS AA, PQT_IL_LOC_BRANCH_DTL a\n" + 
              "         WHERE AA.GIS_LOCATION_ID_FK = A.IL_LOC_ID_FK\n" + 
              "           AND AA.USER_ID_PK = "+  VUserID +")");
    //              setWhereClause("USER_ID_FK =" + VUserID);
              executeQuery();
          }

}

