package pqt.dss.accOpening.model.eo;

import java.sql.SQLException;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 20 16:35:31 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssAccountOpeningLineImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AccOpenHdrFk,
        AccOpnLineIdPk,
        AgentNoFk,
        BankAccNo,
        UserIdFk,
        EnterDate,
        LastUpdatedBy,
        LastUpdatedDate,
        DssAccountOpeningHeader;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ACCOPENHDRFK = AttributesEnum.AccOpenHdrFk.index();
    public static final int ACCOPNLINEIDPK = AttributesEnum.AccOpnLineIdPk.index();
    public static final int AGENTNOFK = AttributesEnum.AgentNoFk.index();
    public static final int BANKACCNO = AttributesEnum.BankAccNo.index();
    public static final int USERIDFK = AttributesEnum.UserIdFk.index();
    public static final int ENTERDATE = AttributesEnum.EnterDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int DSSACCOUNTOPENINGHEADER = AttributesEnum.DssAccountOpeningHeader.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DssAccountOpeningLineImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("pqt.dss.accOpening.model.eo.DssAccountOpeningLine");
    }

    /**
     * Gets the attribute value for AccOpenHdrFk, using the alias name AccOpenHdrFk.
     * @return the value of AccOpenHdrFk
     */
    public Number getAccOpenHdrFk() {
        return (Number) getAttributeInternal(ACCOPENHDRFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccOpenHdrFk.
     * @param value value to set the AccOpenHdrFk
     */
    public void setAccOpenHdrFk(Number value) {
        setAttributeInternal(ACCOPENHDRFK, value);
    }

    /**
     * Gets the attribute value for AccOpnLineIdPk, using the alias name AccOpnLineIdPk.
     * @return the value of AccOpnLineIdPk
     */
    public Number getAccOpnLineIdPk() {
        return (Number) getAttributeInternal(ACCOPNLINEIDPK);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccOpnLineIdPk.
     * @param value value to set the AccOpnLineIdPk
     */
    public void setAccOpnLineIdPk(Number value) {
        setAttributeInternal(ACCOPNLINEIDPK, value);
    }

    /**
     * Gets the attribute value for AgentNoFk, using the alias name AgentNoFk.
     * @return the value of AgentNoFk
     */
    public Number getAgentNoFk() {
        return (Number) getAttributeInternal(AGENTNOFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for AgentNoFk.
     * @param value value to set the AgentNoFk
     */
    public void setAgentNoFk(Number value) {
        setAttributeInternal(AGENTNOFK, value);
    }

    /**
     * Gets the attribute value for BankAccNo, using the alias name BankAccNo.
     * @return the value of BankAccNo
     */
    public String getBankAccNo() {
        return (String) getAttributeInternal(BANKACCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BankAccNo.
     * @param value value to set the BankAccNo
     */
    public void setBankAccNo(String value) {
        setAttributeInternal(BANKACCNO, value);
    }

    /**
     * Gets the attribute value for UserIdFk, using the alias name UserIdFk.
     * @return the value of UserIdFk
     */
    public Number getUserIdFk() {
        return (Number) getAttributeInternal(USERIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserIdFk.
     * @param value value to set the UserIdFk
     */
    public void setUserIdFk(Number value) {
        setAttributeInternal(USERIDFK, value);
    }

    /**
     * Gets the attribute value for EnterDate, using the alias name EnterDate.
     * @return the value of EnterDate
     */
    public Date getEnterDate() {
        return (Date) getAttributeInternal(ENTERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnterDate.
     * @param value value to set the EnterDate
     */
    public void setEnterDate(Date value) {
        setAttributeInternal(ENTERDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * @return the associated entity DssAccountOpeningHeaderImpl.
     */
    public DssAccountOpeningHeaderImpl getDssAccountOpeningHeader() {
        return (DssAccountOpeningHeaderImpl) getAttributeInternal(DSSACCOUNTOPENINGHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity DssAccountOpeningHeaderImpl.
     */
    public void setDssAccountOpeningHeader(DssAccountOpeningHeaderImpl value) {
        setAttributeInternal(DSSACCOUNTOPENINGHEADER, value);
    }


    /**
     * @param accOpnLineIdPk key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number accOpnLineIdPk) {
        return new Key(new Object[] { accOpnLineIdPk });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
     protected void create(AttributeList attributeList) {
         super.create(attributeList);
         Date currentDate = new Date();
         setEnterDate((Date) currentDate.getCurrentDate());
         setLastUpdatedDate((Date) currentDate.getCurrentDate());
         SequenceImpl seq = new SequenceImpl("DSS_ACCOUNT_OPENING_LINE_SEQ", getDBTransaction());
         setAccOpnLineIdPk(seq.getSequenceNumber());
         
         
         FacesContext fctx = FacesContext.getCurrentInstance();
         ExternalContext ectx = fctx.getExternalContext();
         HttpSession userSession = (HttpSession) ectx.getSession(false);
         try {
             setUserIdFk(new Number(userSession.getAttribute("pUserId")));
             setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
         } catch (SQLException ex) {
             setUserIdFk(new Number(0));
             setLastUpdatedBy(new Number(0));
         }
     }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
         * Custom DML update/insert/delete logic here.
         * @param operation the operation type
         * @param e the transaction event
         */
        protected void doDML(int operation, TransactionEvent e) {
            Date currentDate = new Date();
            if (operation == DML_UPDATE) {
                setLastUpdatedDate((Date) currentDate.getCurrentDate());
                FacesContext fctx = FacesContext.getCurrentInstance();
                ExternalContext ectx = fctx.getExternalContext();
                HttpSession userSession = (HttpSession) ectx.getSession(false);
                try {
                    setUserIdFk(new Number(userSession.getAttribute("pUserId")));
                    setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
                } catch (SQLException ex) {
                    setUserIdFk(new Number(0));
                    setLastUpdatedBy(new Number(0));
                }
            }
            super.doDML(operation, e);
        }
}

